from include import Addr_Modes

literal_position = {
    Addr_Modes.IMPLIED:                      0,
    Addr_Modes.ACCUMULATOR:                  0,
    Addr_Modes.IMMEDIATE:                    2,
    Addr_Modes.ABSOLUTE:                     1,
    Addr_Modes.X_INDEXED_ABSOLUTE:           1,
    Addr_Modes.Y_INDEXED_ABSOLUTE:           1,
    Addr_Modes.ABSOLUTE_INDIRECT:            2,
    Addr_Modes.ZERO_PAGE:                    1,
    Addr_Modes.X_INDEXED_ZERO_PAGE:          1,
    Addr_Modes.Y_INDEXED_ZERO_PAGE:          1,
    Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT: 2,
    Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED: 2,
    Addr_Modes.ASSEMBLER_OPTION:             0,
    Addr_Modes.LABEL:                        0,
    Addr_Modes.JUMP_LABEL:                   0,
}

size_in_bytes = {
    Addr_Modes.IMPLIED:                      1,
    Addr_Modes.ACCUMULATOR:                  1,
    Addr_Modes.IMMEDIATE:                    2,
    Addr_Modes.ABSOLUTE:                     3,
    Addr_Modes.X_INDEXED_ABSOLUTE:           3,
    Addr_Modes.Y_INDEXED_ABSOLUTE:           3,
    Addr_Modes.ABSOLUTE_INDIRECT:            3,
    Addr_Modes.ZERO_PAGE:                    2,
    Addr_Modes.X_INDEXED_ZERO_PAGE:          2,
    Addr_Modes.Y_INDEXED_ZERO_PAGE:          2,
    Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT: 2,
    Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED: 2,
    Addr_Modes.ASSEMBLER_OPTION:             0,
    Addr_Modes.LABEL:                        0,
    Addr_Modes.JUMP_LABEL:                   3,
}

arg_types = {
    Addr_Modes.IMPLIED:                      0,
    Addr_Modes.ACCUMULATOR:                  0,
    Addr_Modes.IMMEDIATE:                    8,
    Addr_Modes.ABSOLUTE:                     16,
    Addr_Modes.X_INDEXED_ABSOLUTE:           16,
    Addr_Modes.Y_INDEXED_ABSOLUTE:           16,
    Addr_Modes.ABSOLUTE_INDIRECT:            16,
    Addr_Modes.ZERO_PAGE:                    8,
    Addr_Modes.X_INDEXED_ZERO_PAGE:          8,
    Addr_Modes.Y_INDEXED_ZERO_PAGE:          8,
    Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT: 8,
    Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED: 8,
    Addr_Modes.ASSEMBLER_OPTION:             0,
    Addr_Modes.LABEL:                        0,
    Addr_Modes.JUMP_LABEL:                   16,
}

# mnemonic: [[Supported Addressing Modes], [Hexadecimal bytecodes for each Adressing Mode], [Whether that specific instruction Addresing mode is considered "undocumented" or not]]
instruction_info = {
    'LAS': [[Addr_Modes.Y_INDEXED_ABSOLUTE],
            [0xBB],
            [True]],
    'LAX': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.Y_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xAB, 0xAF, 0xBF, 0xA7, 0xB7, 0xA3, 0xB3],
            [True, True, True, True, True, True, True]],
    'LDA': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xA9, 0xAD, 0xBD, 0xB9, 0xA5, 0xB5, 0xA1, 0xB1],
            [False, False, False, False, False, False, False, False]],
    'LDX': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.Y_INDEXED_ZERO_PAGE],
            [0xA2, 0xAE, 0xBE, 0xA6, 0xB6],
            [False, False, False, False, False]],
    'LDY': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0xA0, 0xAC, 0xBC, 0xA4, 0xB4],
            [False, False, False, False, False]],
    'SAX': [[Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.Y_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT],
            [0x8F, 0x87, 0x97, 0x83],
            [True, True, True, True]],
    'SHA': [[Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x9F, 0x93],
            [True, True]],
    'SHX': [[Addr_Modes.Y_INDEXED_ABSOLUTE],
            [0x9E],
            [True]],
    'SHY': [[Addr_Modes.X_INDEXED_ABSOLUTE],
            [0x9C],
            [True]],
    'STA': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x8D, 0x9D, 0x99, 0x85, 0x95, 0x81, 0x91],
            [False, False, False, False, False, False, False]],
    'STX': [[Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.Y_INDEXED_ZERO_PAGE],
            [0x8E, 0x86, 0x96],
            [False, False, False]],
    'STY': [[Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0x8C, 0x84, 0x94],
            [False, False, False]],
    'SHS': [[Addr_Modes.Y_INDEXED_ABSOLUTE],
            [0x9B],
            [True]],
    'TAX': [[Addr_Modes.IMPLIED],
            [0xAA],
            [False]],
    'TAY': [[Addr_Modes.IMPLIED],
            [0xA8],
            [False]],
    'TSX': [[Addr_Modes.IMPLIED],
            [0xBA],
            [False]],
    'TXA': [[Addr_Modes.IMPLIED],
            [0x8A],
            [False]],
    'TXS': [[Addr_Modes.IMPLIED],
            [0x9A],
            [False]],
    'TYA': [[Addr_Modes.IMPLIED],
            [0x98],
            [False]],
    'PHA': [[Addr_Modes.IMPLIED],
            [0x48],
            [False]],
    'PHP': [[Addr_Modes.IMPLIED],
            [0x08],
            [False]],
    'PLA': [[Addr_Modes.IMPLIED],
            [0x68],
            [False]],
    'PLP': [[Addr_Modes.IMPLIED],
            [0x28],
            [False]],
    'ASL': [[Addr_Modes.ACCUMULATOR, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0x0A, 0x0E, 0x1E, 0x06, 0x16],
            [False, False, False, False, False]],
    'LSR': [[Addr_Modes.ACCUMULATOR, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0x4A, 0x4E, 0x5E, 0x46, 0x56],
            [False, False, False, False, False]],
    'ROL': [[Addr_Modes.ACCUMULATOR, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0x2A, 0x2E, 0x3E, 0x26, 0x36],
            [False, False, False, False, False]],
    'ROR': [[Addr_Modes.ACCUMULATOR, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0x6A, 0x6E, 0x7E, 0x66, 0x76],
            [False, False, False, False, False]],
    'AND': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x29, 0x2D, 0x3D, 0x39, 0x25, 0x35, 0x21, 0x31],
            [False, False, False, False, False, False, False]],
    'BIT': [[Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE],
            [0x2C, 0x24],
            [False, False]],
    'EOR': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x49, 0x4D, 0x5D, 0x59, 0x45, 0x55, 0x41, 0x51],
            [False, False, False, False, False, False, False]],
    'ORA': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x09, 0x0D, 0x1D, 0x19, 0x05, 0x15, 0x01, 0x11],
            [False, False, False, False, False, False, False]],
    'ADC': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x69, 0x6D, 0x7D, 0x79, 0x65, 0x75, 0x61, 0x71],
            [False, False, False, False, False, False, False]],
    # ANC also has an IMMEDIATE addr mode at 0x2B, which is completely redundant, and thus, not implemented
    'ANC': [[Addr_Modes.IMMEDIATE],
            [0x0B],
            [True]],
    'ARR': [[Addr_Modes.IMMEDIATE],
            [0x6B],
            [True]],
    'ASR': [[Addr_Modes.IMMEDIATE],
            [0x4B],
            [True]],
    'CMP': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xC9, 0xCD, 0xDD, 0xD9, 0xC5, 0xD5, 0xC1, 0xD1],
            [False, False, False, False, False, False, False]],
    'CPX': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE],
            [0xE0, 0xEC, 0xE4],
            [False, False, False]],
    'CPY': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.ZERO_PAGE],
            [0xC0, 0xCC, 0xC4],
            [False, False, False]],
    'DCP': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xCF, 0xDF, 0xDB, 0xC7, 0xD7, 0xC3, 0xD3],
            [True, True, True, True, True, True, True]],
    'ISC': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xEF, 0xFF, 0xFB, 0xE7, 0xF7, 0xE3, 0xF3],
            [True, True, True, True, True, True, True]],
    'RLA': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x2F, 0x3F, 0x3B, 0x27, 0x37, 0x23, 0x33],
            [True, True, True, True, True, True, True]],
    'RRA': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x6F, 0x7F, 0x7B, 0x67, 0x77, 0x63, 0x73],
            [True, True, True, True, True, True, True]],
    'SBC': [[Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0xE9, 0xED, 0xFD, 0xF9, 0xE5, 0xF5, 0xE1, 0xF1],
            [False, False, False, False, False, False, False]],
    'SBX': [[Addr_Modes.IMMEDIATE],
            [0xCB],
            [True]],
    'SLO': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x0F, 0x1F, 0x1B, 0x07, 0x17, 0x03, 0x13],
            [True, True, True, True, True, True, True]],
    
    'SRE': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.Y_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE_INDIRECT, Addr_Modes.ZERO_PAGE_INDIRECT_Y_INDEXED],
            [0x4F, 0x5F, 0x5B, 0x47, 0x57, 0x43, 0x53],
            [True, True, True, True, True, True, True]],
    'XXA': [[Addr_Modes.IMMEDIATE],
            [0x8B],
            [True]],
    'DEC': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0xCE, 0xDE, 0xC6, 0xD6],
            [False, False, False, False]],
    'DEX': [[Addr_Modes.IMPLIED],
            [0xCA],
            [False]],
    'DEY': [[Addr_Modes.IMPLIED],
            [0x88],
            [False]],
    'INC': [[Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0xEE, 0xFE, 0xE6, 0xF6],
            [False, False, False, False]],
    'INX': [[Addr_Modes.IMPLIED],
            [0xE8],
            [False]],
    'INY': [[Addr_Modes.IMPLIED],
            [0xC8],
            [False]],
    'BRK': [[Addr_Modes.IMPLIED],
            [0x00],
            [False]],
    'JMP': [[Addr_Modes.ABSOLUTE, Addr_Modes.ABSOLUTE_INDIRECT, Addr_Modes.JUMP_LABEL],
            [0x4C, 0x6C, 0x4C],
            [False, False, False]],
    'JSR': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x20, 0x20],
            [False, False]],
    'RTI': [[Addr_Modes.IMPLIED],
            [0x40],
            [False]],
    'RTS': [[Addr_Modes.IMPLIED],
            [0x60],
            [False]],
    'BCC': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x90, 0x90],
            [False, False]],
    'BCS': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0xB0, 0xB0],
            [False, False]],
    'BEQ': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0xF0, 0xF0],
            [False, False]],
    'BMI': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x30, 0x30],
            [False, False]],
    'BNE': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0xD0, 0xD0],
            [False, False]],
    'BPL': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x10, 0x10],
            [False, False]],
    'BVC': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x50, 0x50],
            [False, False]],
    'BVS': [[Addr_Modes.ABSOLUTE, Addr_Modes.JUMP_LABEL],
            [0x70, 0x70],
            [False, False]],
    'CLC': [[Addr_Modes.IMPLIED],
            [0x18],
            [False]],
    'CLD': [[Addr_Modes.IMPLIED],
            [0xD8],
            [False]],
    'CLI': [[Addr_Modes.IMPLIED],
            [0x58],
            [False]],
    'CLV': [[Addr_Modes.IMPLIED],
            [0xB8],
            [False]],
    'SEC': [[Addr_Modes.IMPLIED],
            [0x38],
            [False]],
    'SED': [[Addr_Modes.IMPLIED],
            [0xF8],
            [False]],
    'SEI': [[Addr_Modes.IMPLIED],
            [0x78],
            [False]],
    # JAM has several implied addr modes, none of which need to be implemented
    'JAM': [[Addr_Modes.IMPLIED],
            [0x02],
            [True]],
    # NOP has several copies of the same addr modes, none of which need to be implemented
    'NOP': [[Addr_Modes.IMPLIED, Addr_Modes.IMMEDIATE, Addr_Modes.ABSOLUTE, Addr_Modes.X_INDEXED_ABSOLUTE, Addr_Modes.ZERO_PAGE, Addr_Modes.X_INDEXED_ZERO_PAGE],
            [0xEA, 0x80, 0x0C, 0x1C, 0x04, 0x14],
            [False, True, True, True, True, True]],
}